### ISSUE TITLE
Tracking issue for PHYSLITE schema

### ISSUE THREAD

**Issue by nikoladze** [scikit-hep/coffea#540]
This is to track the TODO list/open questions for the PHYSLITE schema for nanoevents

- [x] Port ElementLink handling to awkward dask #872 
- [ ] Add a test for a simple selection procedure involving several collections
- [x] Continue with global index forms or to use a different approach? #541
- [ ] Complete the list of mixin classes and add important methods
- ~~Make Records of Unions instead of Unions of Records for the cases with links into multiple collections?~~ (maybe better try not to make unions at all, e.g. for truth collection create a homogeneous record)
- ~~Find out why `ak.where` triggers materialization of a few (but not all) columns~~ (probably different situation now with dask)
- [ ] Silence warnings or add a filter function to be passed to `TBranch.iteritems`
- [x] Add EventInfo collection and check if there are more non-jagged collections #888 
- ~~Zip the HLT collection~~ (this changed in newer PHYSLITE versions, see next point)
- [ ] Find out how trigger info/matching works and how we make it work in columnar analysis
- ~~Find a way to load the hash to branchname mapping from the MetaData tree (or calculate hash manually)~~ (maybe we better hardcode targets for cases where there is only a single one and make a special treatment for truth collection)
- [x] Try out what is/isn't working with newer versions of PHYSLITE
- [ ] Some collections (e.g. TruthMuons) have fiels that can't be zipped (empty lists for some events, so can't use common offsets). How to handle this? Have a list of collections not to zip? Don't zip anything at all?

**Comment by lgray** [comment]
Seems stale.
