### ISSUE TITLE
Tracking for coffea 2023.8.0.rc0

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#800]
new functionality:
- [x] ml_tools: https://github.com/CoffeaTeam/coffea/pull/798 (@yimuchen)
- [x] extensions to PackedSelection: https://github.com/CoffeaTeam/coffea/pull/797 (@iasonkrom)

user code migration easing (processor-based analysis):
- [ ] local executors should use dask task-graphs produced by dask_awkward
- [ ] dask_executor (i.e. distributed) should use dask task-graphs produced by dask_awkward
- [ ] workqueue executor -> taskvine (@btovar)

stretch goals:
- [ ] spark executor ressurection
- [ ] ray testing

dependencies:
- [x] uproot allows chunk specification

@nsmith- @andrzejnovak @jpivarski
